### PR TITLE
Team Chat

### PR DESCRIPTION
**Pull request by Tofixrs**

### CODE REVIEW

**Comment by bay30** [comment]
use table.concat instead of iterating through the array. `table.concat(params," ",2)`
also there is a space in the final string that shouldn't be there `username : message` should be `username: message`

**Comment by Tofixrs** [comment]
> use table.concat instead of iterating through the array. `table.concat(params," ",2)` also there is a space in the final string that shouldn't be there `username : message` should be `username: message`

Done

**Comment by Tofixrs** [comment]
Why did you close this

**Comment by Tofixrs** [comment]
Why close

**Comment by Mel-On-E** [comment]
It's merged into main already

**Comment by Tofixrs** [comment]
Ah ok

**Pull request closed without merging**
